# -*- coding: utf-8 -*-
"""Data Cleansing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pYp9Uz3t0f-YliVq_6_uB4S9r6JXXM6
"""

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "global_startup_success_dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "hamnakaleemds/global-startup-success-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_squared_error

# change categorical "StartupName" to numeric "ID"

df['StartupID'] = df['Startup Name'].str.extract(r'_(\d+)', expand = False).astype('Int64')
# new functions used:
# .str.extract() --> a string accessor method that extract specific patterns from string columns.
# .astype(int) --> converts the extracted number from string to integer type.

df = df.drop(columns = ['Startup Name'])
cols = list(df.columns)
cols.remove('StartupID')
cols.insert(0, 'StartupID')
df = df[cols]



print(df.head(50))